version: '3.8'

services:

  app:
    container_name: app-node
    build:
      context: ./node
      dockerfile: dockerfile
    volumes:
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "yarn install && yarn run start"
    tty: true
    depends_on:
      - db
    networks:
      - web-network
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - '8080:80'
    depends_on:
      - app
      - db
    networks:
      - web-network

  db:
    container_name: mysql-db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./node/script/mysql:/docker-entrypoint-initdb.d/:rw
    environment:
      - MYSQL_DATABASE=people
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - web-network

networks:
  web-network:
    driver: bridge